Repository gp3pi/projeto-integrador-frontend, pull requests merged in 2022-09, with the labels that each got.

#19 Incrementando o SobreNos.css e organizando a página
  src/paginas/sobrenos/SobreNos.css
  src/paginas/sobrenos/SobreNos.tsx
Labels: Code review finalizado

#20 Feature/login
  package-lock.json
  package.json
  src/App.tsx
  src/componentes/estaticos/footer/Footer.css
  src/componentes/estaticos/footer/Footer.tsx
  src/componentes/estaticos/navbar/Navbar.css
  src/componentes/estaticos/navbar/Navbar.tsx
  src/paginas/home/Home.tsx
  src/paginas/home/images/homepicturetemporaria.png
  src/paginas/login/Login.css
  src/paginas/login/Login.tsx
  src/paginas/sobrenos/SobreNos.css
  src/paginas/sobrenos/SobreNos.tsx
  yarn.lock
Labels: Code review finalizado

#30 Feature/cadastro
  src/App.tsx
  src/paginas/cadastro/Cadastro.css
  src/paginas/cadastro/Cadastro.tsx
Labels: Code review finalizado

#31 css provisório da home, falta imagem apropriada, background provisório
  package.json
  src/paginas/home/Home.css
  src/paginas/home/Home.tsx
  yarn.lock
Labels: Code review finalizado

#32 Footer
  src/componentes/estaticos/footer/Footer.css
  src/componentes/estaticos/footer/Footer.tsx
  src/models/User.ts
  src/models/UserLogin.ts
  src/paginas/cadastro/Cadastro.tsx
  src/paginas/home/Home.tsx
  src/paginas/login/Login.tsx
  src/services/Service.ts
Labels: Code review finalizado

#33 Estrura do componente SobreNos e adição de texto
  src/paginas/sobrenos/SobreNos.css
  src/paginas/sobrenos/SobreNos.tsx
Labels: Code review finalizado

#36 Criando conexão com Back-end, e implementando regra de négocios.
  src/componentes/estaticos/footer/Footer.css
  src/paginas/cadastro/Cadastro.css
  src/paginas/cadastro/Cadastro.tsx
Labels: Code review finalizado

#37 Feature/navbar
  src/componentes/estaticos/navbar/Navbar.css
  src/componentes/estaticos/navbar/Navbar.tsx
Labels: Aguardando code review

#38 banner com o logo na pág Sobre Nos
  src/paginas/sobrenos/SobreNos.css
  src/paginas/sobrenos/SobreNos.tsx
  src/paginas/sobrenos/img/banner.png
Labels: Code review finalizado

#42 adição do componente Temas
  src/App.tsx
  src/componentes/temas/cadastroTemas/CadastroTemas.css
  src/componentes/temas/cadastroTemas/CadastroTemas.tsx
  src/componentes/temas/deletarTemas/DeletarTemas.css
  src/componentes/temas/deletarTemas/DeletarTemas.tsx
  src/componentes/temas/listaTemas/ListaTemas.css
  src/componentes/temas/listaTemas/ListaTemas.tsx
  src/models/Temas.ts
  src/services/Service.ts
Labels: Aguardando code review

#43 Feature/css
  src/paginas/cadastro/Cadastro.css
  src/paginas/cadastro/Cadastro.tsx
  src/paginas/home/Home.css
  src/paginas/home/Home.tsx
  src/paginas/login/Login.css
  src/paginas/login/Login.tsx
Labels: Code review finalizado

#44 Adicionando o Deletar Postagem e o TabPostagem
  src/App.tsx
  src/componentes/postagens/deletarPostagem/DeletarPostagem.css
  src/componentes/postagens/deletarPostagem/DeletarPostagem.tsx
  src/componentes/postagens/listaPostagem/ListaPostagem.tsx
  src/componentes/postagens/tabPostagem/TabPostagem.css
  src/componentes/postagens/tabPostagem/TabPostagem.tsx
  src/componentes/temas/deletarTema/DeletarTema.css
  src/models/Postagem.ts
  src/services/Service.ts
Labels: Aguardando code review

#46 Adicionando imagem às postagens e estilizando os cards de ListaPostagem
  src/componentes/postagens/cadastrarPostagem/CadastroPostagem.tsx
  src/componentes/postagens/listaPostagem/ListaPostagem.css
  src/componentes/postagens/listaPostagem/ListaPostagem.tsx
  src/models/Postagem.ts
  src/services/Service.ts
Labels: Code review finalizado

#49 Adicionando delete na postagem.
  src/componentes/postagens/deletarPostagem/DeletarPostagem.tsx
Labels: Code review finalizado

#51 Feature/redux
  src/App.tsx
  src/componentes/estaticos/footer/Footer.tsx
  src/componentes/estaticos/navbar/Navbar.tsx
  src/componentes/postagens/cadastrarPostagem/CadastroPostagem.tsx
  src/componentes/postagens/deletarPostagem/DeletarPostagem.tsx
  src/componentes/postagens/listaPostagem/ListaPostagem.tsx
  src/componentes/temas/cadastrarTemas/CadastrarTema.tsx
  src/componentes/temas/deletarTema/DeletarTemas.tsx
  src/componentes/temas/listaTemas/ListaTemas.tsx
  src/paginas/home/Home.tsx
  src/paginas/login/Login.tsx
  src/store/store.ts
  src/store/tokens/actions.ts
  src/store/tokens/tokensReducer.ts
Labels: Finalizado

#53 Feature/foto postagem
  src/App.tsx
  src/componentes/postagens/deletarPostagem/DeletarPostagem.tsx
  src/componentes/postagens/listaPostagem/ListaPostagem.css
  src/componentes/postagens/listaPostagem/ListaPostagem.tsx
  src/paginas/cadastro/Cadastro.tsx
  src/paginas/home/Home.tsx
  src/paginas/login/Login.tsx
Labels: Code review finalizado

#54 Feature/tostify
  src/App.tsx
  src/componentes/estaticos/navbar/Navbar.tsx
  src/componentes/postagens/cadastrarPostagem/CadastroPostagem.tsx
  src/componentes/postagens/deletarPostagem/DeletarPostagem.tsx
  src/componentes/postagens/modalPostagem/ModalPostagem.tsx
  src/componentes/postagens/tabPostagem/TabPostagem.tsx
  src/componentes/temas/cadastrarTemas/CadastrarTema.tsx
  src/componentes/temas/deletarTema/DeletarTemas.tsx
  src/componentes/temas/modalTema/ModalTema.tsx
  src/paginas/cadastro/Cadastro.tsx
  src/paginas/home/Home.css
  src/paginas/home/Home.tsx
  src/paginas/login/Login.tsx
Labels: Code review finalizado

#56 Feature/tostify
  src/componentes/temas/listaTemas/ListaTemas.tsx
  src/paginas/home/Home.css
  src/paginas/home/Home.tsx
Labels: Code review finalizado

#57 Alteração dos alerts de erro de Postagem
  package.json
  src/componentes/postagens/cadastrarPostagem/CadastroPostagem.tsx
  yarn.lock
Labels: Aguardando code review

#58 Feature/foto postagem
  src/componentes/postagens/modalPostagem/ModalPostagem.css
  src/componentes/postagens/modalPostagem/ModalPostagem.tsx
  src/componentes/temas/modalTema/ModalTema.css
  src/componentes/temas/modalTema/ModalTema.tsx
  src/paginas/home/Home.css
  src/paginas/home/Home.tsx
Labels: Aguardando code review

#68 Finalizando estilização das postagens no componente ListaPostagem
  src/componentes/postagens/listaPostagem/ListaPostagem.css
  src/componentes/postagens/listaPostagem/ListaPostagem.tsx
Labels: Code review finalizado

#67 Feature/quero ajudar
  src/App.tsx
  src/componentes/estaticos/navbar/Navbar.css
  src/componentes/estaticos/navbar/Navbar.tsx
  src/paginas/queroAjudar/QueroAjudar.css
  src/paginas/queroAjudar/QueroAjudar.tsx
Labels: Aguardando code review

#73 Feature/logo login
  src/paginas/login/Login.css
  src/paginas/login/Login.tsx
  src/paginas/login/imag/TelkLogo.png
Labels: Aguardando code review

#70 Feature/finalizacao
  src/paginas/queroAjudar/01.jpg
  src/paginas/queroAjudar/QueroAjudar.css
  src/paginas/queroAjudar/QueroAjudar.tsx
  src/paginas/queroAjudar/Sem título.jpg
Labels: Aguardando code review

#75 Feature/navbar
  src/componentes/estaticos/navbar/Navbar.css
  src/componentes/estaticos/navbar/Navbar.tsx
  src/paginas/login/Login.css
Labels: Finalizado

#76 Estilização do Quero Ajudar
  package.json
  src/componentes/Carrossel/Carrossel.css
  src/componentes/Carrossel/Carrossel.tsx
  src/paginas/queroAjudar/01.jpg
  src/paginas/queroAjudar/QueroAjudar.css
  src/paginas/queroAjudar/QueroAjudar.tsx
  src/paginas/queroAjudar/Sem título.jpg
  yarn.lock
Labels: Code review finalizado

#77 Fav icon alterado e finalização do Sobre Nós
  public/index.html
  src/paginas/sobrenos/SobreNos.css
  src/paginas/sobrenos/SobreNos.tsx
Labels: Finalizado

#78 Ajustes finais no CSS do site
  src/componentes/estaticos/footer/Footer.css
  src/componentes/estaticos/footer/Footer.tsx
  src/componentes/postagens/cadastrarPostagem/CadastroPostagem.css
  src/componentes/postagens/cadastrarPostagem/CadastroPostagem.tsx
  src/componentes/postagens/deletarPostagem/DeletarPostagem.css
  src/componentes/postagens/deletarPostagem/DeletarPostagem.tsx
  src/componentes/postagens/modalPostagem/ModalPostagem.css
  src/componentes/postagens/modalPostagem/ModalPostagem.tsx
  src/componentes/temas/cadastrarTemas/CadastrarTema.css
  src/componentes/temas/cadastrarTemas/CadastrarTema.tsx
  src/componentes/temas/deletarTema/DeletarTema.css
  src/componentes/temas/deletarTema/DeletarTemas.tsx
  src/paginas/queroAjudar/QueroAjudar.css
  src/paginas/queroAjudar/QueroAjudar.tsx
Labels: Finalizado

#79 Ajustando viewport dos componentes CadastroPostagem e CadastroTema
  src/componentes/temas/cadastrarTemas/CadastrarTema.css
Labels: Finalizado

#80 Ajustando bordas dos componentes Modal
  src/componentes/postagens/modalPostagem/ModalPostagem.css
Labels: Finalizado

#81 Ajustando bordas do componente ModalTema
  src/componentes/postagens/modalPostagem/ModalPostagem.css
  src/componentes/temas/modalTema/ModalTema.css
Labels: Finalizado
