Repository gp3pi/projeto-integrador-frontend, pull requests merged in 2022-08, with the labels that each got.

#8 Criando o rodapé da rede social.
  src/App.tsx
  src/componentes/estaticos/footer/Footer.css
  src/componentes/estaticos/footer/Footer.tsx
Labels: Code review finalizado

#9 Feature/login
  package.json
  src/App.tsx
  src/paginas/login/Login.css
  src/paginas/login/Login.tsx
  yarn.lock
Labels: Finalizado

#11 criando componente sobre nós
  src/App.tsx
  src/paginas/sobrenos/SobreNos.css
  src/paginas/sobrenos/SobreNos.tsx
Labels: Aguardando code review

#12 Criando o componente Navbar
  src/App.tsx
  src/componentes/estaticos/navbar/Navbar.css
  src/componentes/estaticos/navbar/Navbar.tsx
Labels: Aguardando code review

#13 Adicionando as rotas
  src/App.tsx
  src/componentes/estaticos/navbar/Navbar.tsx
  src/paginas/login/Login.tsx
Labels: Code review finalizado
